/**
 * Offline generator for `fixtures/ecdsa-p256-vectors.json`.
 *
 * Produces P-256 ECDSA vectors using node:crypto's ec key pair API +
 * raw signing, encoded as 6 × 43-bit little-endian limbs to match the
 * EcdsaP256Verify circuit input shape.
 *
 * Re-run with: `npx ts-node scripts/gen-ecdsa-p256-vectors.ts`. Output
 * is non-deterministic across runs (fresh keypair, fresh signature) but
 * stable enough for fixture purposes.
 */
import {
  createHash,
  createPrivateKey,
  createPublicKey,
  generateKeyPairSync,
  sign as nodeSign,
} from 'node:crypto';
import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const N_BITS = 43n;
const K_LIMBS = 6;

function bigIntToLimbsLE(x: bigint): string[] {
  const mask = (1n << N_BITS) - 1n;
  const out: string[] = [];
  let cur = x;
  for (let i = 0; i < K_LIMBS; i++) {
    out.push((cur & mask).toString());
    cur >>= N_BITS;
  }
  if (cur !== 0n) {
    throw new Error('value does not fit in K_LIMBS × N_BITS');
  }
  return out;
}

// Convert raw 32-byte big-endian buffer to bigint.
function bufBeToBigInt(buf: Buffer): bigint {
  let acc = 0n;
  for (const b of buf) acc = (acc << 8n) | BigInt(b);
  return acc;
}

// node's pubkey JWK gives us x and y in base64url BE bytes.
function jwkPublicXY(pubKey: ReturnType<typeof createPublicKey>): {
  x: bigint;
  y: bigint;
} {
  const jwk = pubKey.export({ format: 'jwk' }) as { x: string; y: string };
  return {
    x: bufBeToBigInt(Buffer.from(jwk.x, 'base64url')),
    y: bufBeToBigInt(Buffer.from(jwk.y, 'base64url')),
  };
}

// node:crypto returns ECDSA sigs in DER. Decode the (r, s) integers.
function decodeDerEcdsaSig(der: Buffer): { r: bigint; s: bigint } {
  // SEQUENCE(0x30) len INT(0x02) lenR R INT(0x02) lenS S
  if (der[0] !== 0x30) throw new Error('not a DER SEQUENCE');
  let off = 2;
  if (der[1]! & 0x80) off = 2 + (der[1]! & 0x7f);
  if (der[off] !== 0x02) throw new Error('expected INTEGER for r');
  const rLen = der[off + 1]!;
  let r = bufBeToBigInt(der.subarray(off + 2, off + 2 + rLen));
  off += 2 + rLen;
  if (der[off] !== 0x02) throw new Error('expected INTEGER for s');
  const sLen = der[off + 1]!;
  let s = bufBeToBigInt(der.subarray(off + 2, off + 2 + sLen));
  return { r, s };
}

// node:crypto with namedCurve 'prime256v1' = P-256.
const { privateKey, publicKey } = generateKeyPairSync('ec', { namedCurve: 'prime256v1' });
const { x: pubX, y: pubY } = jwkPublicXY(publicKey);

const message = Buffer.from('zkqes Phase 1 ECDSA P-256 test vector', 'utf8');
const msghashBuf = createHash('sha256').update(message).digest();
const msghash = bufBeToBigInt(msghashBuf);

// Sign the *digest* directly. We use 'sha256' here as the digest algorithm,
// passing the raw message; node hashes internally and produces a DER sig.
const sigDer = nodeSign('sha256', message, privateKey);
const { r, s } = decodeDerEcdsaSig(sigDer);

// Generate a second unrelated keypair for the wrong-pubkey case.
const { publicKey: otherPub } = generateKeyPairSync('ec', { namedCurve: 'prime256v1' });
const { x: otherX, y: otherY } = jwkPublicXY(otherPub);

// P-256 group order (n).
const N_P256 =
  0xffffffff00000000ffffffffffffffffbce6faada7179e84f3b9cac2fc632551n;

// Tampered r: add 1 mod n.
const rTampered = (r + 1n) % N_P256;
// Tampered s: also add 1 mod n.
const sTampered = (s + 1n) % N_P256;

const fixture = {
  description:
    'ECDSA P-256 + SHA-256 test vectors for EcdsaP256Verify (n=43, k=6, ' +
    'limbs LE). Generated by scripts/gen-ecdsa-p256-vectors.ts.',
  params: { nBits: Number(N_BITS), kLimbs: K_LIMBS, curve: 'prime256v1' },
  cases: {
    valid: {
      label: 'valid signature over sha256(message)',
      msghash: bigIntToLimbsLE(msghash),
      r: bigIntToLimbsLE(r),
      s: bigIntToLimbsLE(s),
      pubkey: [bigIntToLimbsLE(pubX), bigIntToLimbsLE(pubY)],
      shouldVerify: true,
    },
    tamperedR: {
      label: 'r incremented by 1 mod n',
      msghash: bigIntToLimbsLE(msghash),
      r: bigIntToLimbsLE(rTampered),
      s: bigIntToLimbsLE(s),
      pubkey: [bigIntToLimbsLE(pubX), bigIntToLimbsLE(pubY)],
      shouldVerify: false,
    },
    tamperedS: {
      label: 's incremented by 1 mod n',
      msghash: bigIntToLimbsLE(msghash),
      r: bigIntToLimbsLE(r),
      s: bigIntToLimbsLE(sTampered),
      pubkey: [bigIntToLimbsLE(pubX), bigIntToLimbsLE(pubY)],
      shouldVerify: false,
    },
    wrongPubkey: {
      label: 'valid signature against an unrelated keypair',
      msghash: bigIntToLimbsLE(msghash),
      r: bigIntToLimbsLE(r),
      s: bigIntToLimbsLE(s),
      pubkey: [bigIntToLimbsLE(otherX), bigIntToLimbsLE(otherY)],
      shouldVerify: false,
    },
  },
};

const outPath = resolve(__dirname, '..', 'fixtures', 'ecdsa-p256-vectors.json');
writeFileSync(outPath, `${JSON.stringify(fixture, null, 2)}\n`, 'utf8');
console.log(`Wrote ${outPath}`);
