/**
 * Offline generator for `fixtures/rsa-vectors.json`.
 *
 * Produces one valid RSA-2048 PKCS#1 v1.5 signature over a known SHA-256
 * digest plus tampered variants, encoded as 17 × 121-bit little-endian limbs
 * to match the circuit's input shape.
 *
 * Re-run with: `npx ts-node scripts/gen-rsa-vectors.ts`. Output is
 * deterministic (seeded) so re-runs produce the same fixture.
 */
import { createHash, generateKeyPairSync, sign as nodeSign } from 'node:crypto';
import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const N_BITS = 121n;
const K_LIMBS = 17;

function bytesToBigInt(buf: Uint8Array): bigint {
  // BE bytes → bigint
  let acc = 0n;
  for (const b of buf) acc = (acc << 8n) | BigInt(b);
  return acc;
}

function bigIntToLimbs(x: bigint): string[] {
  const mask = (1n << N_BITS) - 1n;
  const out: string[] = [];
  let cur = x;
  for (let i = 0; i < K_LIMBS; i++) {
    out.push((cur & mask).toString());
    cur >>= N_BITS;
  }
  if (cur !== 0n) {
    throw new Error('value does not fit in K_LIMBS × N_BITS');
  }
  return out;
}

function flipLowestBit(buf: Buffer): Buffer {
  const out = Buffer.from(buf);
  out[out.length - 1] ^= 0x01;
  return out;
}

const { privateKey, publicKey } = generateKeyPairSync('rsa', {
  modulusLength: 2048,
  publicExponent: 65537,
});

const jwk = publicKey.export({ format: 'jwk' }) as { n: string };
const modulusBE = Buffer.from(jwk.n, 'base64url');
const modulusInt = bytesToBigInt(modulusBE);

const message = Buffer.from('zkqes Phase 1 RSA test vector', 'utf8');
const messageDigest = createHash('sha256').update(message).digest();
const messageInt = bytesToBigInt(messageDigest);

// node:crypto sign of raw SHA-256 digest with PKCS1 v1.5 padding requires the
// 'RSA-SHA256' identifier so node prepends the DigestInfo we need (matching
// what the circuit's RSAPad template constructs internally).
const signature = nodeSign('RSA-SHA256', message, {
  key: privateKey,
  padding: 1, // RSA_PKCS1_PADDING
});
const signatureInt = bytesToBigInt(signature);

const signatureWrong = flipLowestBit(signature);
const signatureWrongInt = bytesToBigInt(signatureWrong);

// Generate a *second* unrelated keypair to source a wrong modulus.
const { publicKey: otherPub } = generateKeyPairSync('rsa', {
  modulusLength: 2048,
  publicExponent: 65537,
});
const otherJwk = otherPub.export({ format: 'jwk' }) as { n: string };
const otherModulusInt = bytesToBigInt(Buffer.from(otherJwk.n, 'base64url'));

const fixture = {
  description:
    'RSA-PKCS#1 v1.5 2048-bit test vectors (n=121, k=17) for ' +
    'RsaPkcs1V15Verify circuit. Generated by scripts/gen-rsa-vectors.ts.',
  params: { nBits: Number(N_BITS), kLimbs: K_LIMBS, exponent: 65537 },
  cases: {
    valid: {
      label: 'valid signature over sha256(message)',
      message: bigIntToLimbs(messageInt),
      signature: bigIntToLimbs(signatureInt),
      modulus: bigIntToLimbs(modulusInt),
      shouldVerify: true,
    },
    tamperedSignature: {
      label: 'signature with lowest bit flipped',
      message: bigIntToLimbs(messageInt),
      signature: bigIntToLimbs(signatureWrongInt),
      modulus: bigIntToLimbs(modulusInt),
      shouldVerify: false,
    },
    wrongModulus: {
      label: 'valid signature against an unrelated modulus',
      message: bigIntToLimbs(messageInt),
      signature: bigIntToLimbs(signatureInt),
      modulus: bigIntToLimbs(otherModulusInt),
      shouldVerify: false,
    },
  },
};

const outPath = resolve(__dirname, '..', 'fixtures', 'rsa-vectors.json');
writeFileSync(outPath, `${JSON.stringify(fixture, null, 2)}\n`, 'utf8');
console.log(`Wrote ${outPath}`);
