/**
 * Generates `circuits/binding/DeclarationWhitelist.circom` from the
 * canonical digests in `fixtures/declarations/digests.json`.
 *
 * Rationale: hand-coding 512 bits is error-prone. This script is the
 * single source of truth that converts the hex digests to MSB-first
 * bit arrays inside the circom file. Re-run any time digests.json
 * changes (which itself is a breaking change requiring a new ceremony).
 *
 * Usage: `npx ts-node scripts/regen-declaration-whitelist.ts`.
 *
 * Companion: `scripts/verify-declaration-digests.sh` re-hashes en.txt
 * and uk.txt at build time and checks the in-circuit constants haven't
 * drifted vs digests.json.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const repoRoot = resolve(__dirname, '..', '..', '..');
const digestsPath = resolve(repoRoot, 'fixtures', 'declarations', 'digests.json');
const outPath = resolve(
  __dirname,
  '..',
  'circuits',
  'binding',
  'DeclarationWhitelist.circom',
);

interface DigestsFile {
  declarations: { en: { sha256: string }; uk: { sha256: string } };
}
const digests = JSON.parse(readFileSync(digestsPath, 'utf8')) as DigestsFile;
const enHex = digests.declarations.en.sha256.replace(/^0x/, '');
const ukHex = digests.declarations.uk.sha256.replace(/^0x/, '');

function hexToBitsMsbFirst(hex: string): number[] {
  if (hex.length !== 64) throw new Error(`expected 64 hex chars, got ${hex.length}`);
  const bytes: number[] = [];
  for (let i = 0; i < 32; i++) bytes.push(parseInt(hex.slice(i * 2, i * 2 + 2), 16));
  const bits: number[] = [];
  for (const b of bytes) {
    for (let i = 7; i >= 0; i--) bits.push((b >> i) & 1);
  }
  return bits;
}

function fmtRow(bits: number[], indent: string): string {
  // 8 bits per group, 4 groups per row → 32 bits per row.
  const rows: string[] = [];
  for (let r = 0; r < bits.length; r += 32) {
    const groups: string[] = [];
    for (let g = 0; g < 4; g++) {
      const start = r + g * 8;
      groups.push(bits.slice(start, start + 8).join(','));
    }
    rows.push(indent + groups.join(', '));
  }
  return rows.join(',\n');
}

const enBits = hexToBitsMsbFirst(enHex);
const ukBits = hexToBitsMsbFirst(ukHex);

const out = `pragma circom 2.1.9;

// DeclarationWhitelist
//
// Asserts that a SHA-256 digest equals one of the two pinned canonical
// declaration digests (EN or UK). The digests are hard-coded constants;
// changing them is a breaking change requiring a new circuit version and
// a new ceremony.
//
// Source of truth: \`fixtures/declarations/digests.json\`.
// This file is generated by \`scripts/regen-declaration-whitelist.ts\`;
// do not edit by hand. The companion \`scripts/verify-declaration-digests.sh\`
// re-hashes en.txt and uk.txt at build time and asserts the constants
// below haven't drifted.
//
//   EN sha256 = 0x${enHex}
//   UK sha256 = 0x${ukHex}
//
// Input: \`digestBits[256]\` — output of Sha256Bytes / Sha256Var in the
// MSB-first bit order zk-email produces (bit i = (byte[i/8] >> (7 -
// (i%8))) & 1).
//
// Constraint-only template (no outputs).

template DeclarationWhitelist() {
    signal input digestBits[256];

    var EN[256] = [
${fmtRow(enBits, '        ')}
    ];

    var UK[256] = [
${fmtRow(ukBits, '        ')}
    ];

    // Per-bit XNOR via algebraic identity:
    //   matchEn[i] = 1 iff digestBits[i] == EN[i]
    //              = 1 - digestBits[i] - EN[i] + 2 * digestBits[i] * EN[i]
    signal matchEnBit[256];
    signal matchUkBit[256];
    for (var i = 0; i < 256; i++) {
        matchEnBit[i] <== 1 - digestBits[i] - EN[i] + 2 * digestBits[i] * EN[i];
        matchUkBit[i] <== 1 - digestBits[i] - UK[i] + 2 * digestBits[i] * UK[i];
    }

    // 256-wide AND via mul-chain.
    signal enChain[256];
    signal ukChain[256];
    enChain[0] <== matchEnBit[0];
    ukChain[0] <== matchUkBit[0];
    for (var i = 1; i < 256; i++) {
        enChain[i] <== enChain[i - 1] * matchEnBit[i];
        ukChain[i] <== ukChain[i - 1] * matchUkBit[i];
    }

    // (a OR b) where a, b ∈ {0,1}: a + b - a*b.
    signal isEn;
    signal isUk;
    isEn <== enChain[255];
    isUk <== ukChain[255];
    isEn + isUk - isEn * isUk === 1;
}

component main = DeclarationWhitelist();
`;

writeFileSync(outPath, out, 'utf8');
console.log(`Wrote ${outPath}`);
console.log(`EN digest: 0x${enHex}`);
console.log(`UK digest: 0x${ukHex}`);
