// Canonical QIE error codes (frozen per orchestration §2.5).
export const QIE_ERRORS = {
  AGENT_UNREACHABLE: "QIE_AGENT_UNREACHABLE",
  PREDICATE_UNSATISFIED: "QIE_PREDICATE_UNSATISFIED",
  ESCROW_EXPIRED: "QIE_ESCROW_EXPIRED",
  ESCROW_REVOKED: "QIE_ESCROW_REVOKED",
  ESCROW_NOT_FOUND: "QIE_ESCROW_NOT_FOUND",
  CONFIG_MISMATCH: "QIE_CONFIG_MISMATCH",
  SHARE_DECRYPT_FAILED: "QIE_SHARE_DECRYPT_FAILED",
  RECONSTRUCTION_FAILED: "QIE_RECONSTRUCTION_FAILED",
  LOTL_AGENT_UNKNOWN: "QIE_LOTL_AGENT_UNKNOWN",
  REPLAY_DETECTED: "QIE_REPLAY_DETECTED",
  RATE_LIMITED: "QIE_RATE_LIMITED",
  // MVP refinement §0.5 — notary-assisted recovery + state machine.
  NOTARY_CHAIN_UNTRUSTED: "QIE_NOTARY_CHAIN_UNTRUSTED",
  NOTARY_SIG_BAD: "QIE_NOTARY_SIG_BAD",
  NOTARY_MISMATCH: "QIE_NOTARY_MISMATCH",
  ESCROW_WRONG_STATE: "QIE_ESCROW_WRONG_STATE",
} as const;

export type QIEErrorCode = typeof QIE_ERRORS[keyof typeof QIE_ERRORS];
