// SPDX-License-Identifier: GPL-3.0-or-later
pragma solidity 0.8.24;

import {Test} from "forge-std/Test.sol";
import {PoseidonMerkle} from "../src/libs/PoseidonMerkle.sol";
import {Poseidon} from "../src/libs/Poseidon.sol";
import {PoseidonBytecode} from "../src/libs/PoseidonBytecode.sol";

/// @notice Tests for V5 PoseidonMerkle library — §4 of the contracts plan.
/// All fixtures are generated by
/// `script/generate-merkle-fixtures.ts` (committed alongside) and
/// pinned at `test/fixtures/v5/merkle.json`. The fixture's reference
/// values come from circomlibjs's poseidon_reference.js.
///
/// Coverage:
///   - Acceptance: every (leaf, path, pathBits, root) tuple in the fixture
///     verifies true. Three trees: single-leaf (proof traverses all
///     16 empty siblings), five-leaves (mixed left/right paths), and
///     right-edge-65535 (pathBits = all-ones, fully-populated bottom layer).
///   - Negative: tampering ANY of (leaf, sibling[k], pathBits[k], root)
///     flips the result to false.
contract PoseidonMerkleTest is Test {
    string internal constant FIXTURE = "./packages/contracts/test/fixtures/v5/merkle.json";

    address internal t3;

    struct Proof {
        uint256 index;
        bytes32 leaf;
        uint256 pathBits;
        bytes32[16] siblings;
    }

    function setUp() public {
        t3 = Poseidon.deploy(PoseidonBytecode.t3Initcode());
    }

    /* --- acceptance --- */

    function test_verify_singleLeaf_at_index0() public view {
        (bytes32 root, Proof memory p) = _readCaseProof("single-leaf", 0);
        assertTrue(PoseidonMerkle.verify(t3, p.leaf, p.siblings, p.pathBits, root));
    }

    function test_verify_fiveLeaves_each_index_passes() public view {
        for (uint256 i = 0; i < 5; i++) {
            (bytes32 root, Proof memory p) = _readCaseProof("five-leaves", i);
            assertTrue(
                PoseidonMerkle.verify(t3, p.leaf, p.siblings, p.pathBits, root),
                "five-leaves proof failed"
            );
        }
    }

    function test_verify_rightEdge_index65535_pathBits_allOnes() public view {
        (bytes32 root, Proof memory p) = _readCaseProof("right-edge-65535", 65535);
        // Sanity: pathBits should equal 0xffff (all 16 low bits set) for
        // the right-edge leaf in a fully-populated depth-16 tree.
        assertEq(p.pathBits & 0xFFFF, 0xFFFF, "rightmost leaf should have all-ones pathBits");
        assertTrue(PoseidonMerkle.verify(t3, p.leaf, p.siblings, p.pathBits, root));
    }

    /* --- negative --- */

    function test_verify_fails_for_tampered_leaf() public view {
        (bytes32 root, Proof memory p) = _readCaseProof("five-leaves", 2);
        bytes32 tampered = bytes32(uint256(p.leaf) ^ 1);
        assertFalse(PoseidonMerkle.verify(t3, tampered, p.siblings, p.pathBits, root));
    }

    function test_verify_fails_for_tampered_first_sibling() public view {
        (bytes32 root, Proof memory p) = _readCaseProof("five-leaves", 1);
        p.siblings[0] = bytes32(uint256(p.siblings[0]) ^ 1);
        assertFalse(PoseidonMerkle.verify(t3, p.leaf, p.siblings, p.pathBits, root));
    }

    function test_verify_fails_for_tampered_top_sibling() public view {
        (bytes32 root, Proof memory p) = _readCaseProof("five-leaves", 3);
        p.siblings[15] = bytes32(uint256(p.siblings[15]) ^ 1);
        assertFalse(PoseidonMerkle.verify(t3, p.leaf, p.siblings, p.pathBits, root));
    }

    function test_verify_fails_for_flipped_pathBit() public view {
        (bytes32 root, Proof memory p) = _readCaseProof("five-leaves", 4);
        // Flip bit 0 — for index 4 in five-leaves the original bit-0 was 0
        // (4 is even ⇒ left child at level 0). Flipping makes the verifier
        // hash siblings in the wrong order and miss the root.
        uint256 flipped = p.pathBits ^ 1;
        assertFalse(PoseidonMerkle.verify(t3, p.leaf, p.siblings, flipped, root));
    }

    function test_verify_fails_for_wrong_root() public view {
        (bytes32 root, Proof memory p) = _readCaseProof("five-leaves", 0);
        bytes32 wrong = bytes32(uint256(root) ^ 1);
        assertFalse(PoseidonMerkle.verify(t3, p.leaf, p.siblings, p.pathBits, wrong));
    }

    /* --- fixture reader (substring search; same posture as SpkiCommitParity) --- */

    function _readCaseProof(string memory caseLabel, uint256 proofIndex)
        internal
        view
        returns (bytes32 root, Proof memory proof)
    {
        string memory json = vm.readFile(FIXTURE);
        bytes memory j = bytes(json);

        // Locate the case body by label.
        bytes memory labelKey = bytes(string.concat('"label": "', caseLabel, '"'));
        uint256 caseAt = _indexOf(j, labelKey, 0);
        require(caseAt != type(uint256).max, "case label not found");

        // Find the case's `root` field.
        root = bytes32(_readHexField(j, "root", caseAt));

        // Walk into the `proofs` array and find the proofIndex-th entry by
        // matching "index": N.
        bytes memory idxKey = bytes(string.concat('"index": ', _utoa(proofIndex)));
        uint256 idxAt = _indexOf(j, idxKey, caseAt);
        require(idxAt != type(uint256).max, "proof index not found");

        proof.index = proofIndex;
        proof.leaf = bytes32(_readHexField(j, "leaf", idxAt));
        proof.pathBits = _readHexField(j, "pathBits", idxAt);

        // siblings: an array of 16 0x-prefixed hex strings.
        bytes memory sibKey = bytes('"siblings"');
        uint256 sibAt = _indexOf(j, sibKey, idxAt);
        require(sibAt != type(uint256).max, "siblings not found");
        uint256 cursor = sibAt + sibKey.length;
        for (uint256 k = 0; k < 16; k++) {
            uint256 q1 = _indexOfChar(j, 0x22 /* " */, cursor);
            require(q1 != type(uint256).max, "sibling open-quote");
            uint256 q2 = _indexOfChar(j, 0x22, q1 + 1);
            require(q2 != type(uint256).max, "sibling close-quote");
            proof.siblings[k] = bytes32(_decodeHexWord(_slice(j, q1 + 1, q2)));
            cursor = q2 + 1;
        }
    }

    function _readHexField(bytes memory j, string memory name, uint256 from)
        internal
        pure
        returns (uint256)
    {
        bytes memory key = bytes(string.concat('"', name, '"'));
        uint256 keyAt = _indexOf(j, key, from);
        require(keyAt != type(uint256).max, name);
        uint256 colonAt = _indexOfChar(j, 0x3A, keyAt + key.length);
        require(colonAt != type(uint256).max, "no colon");
        uint256 q1 = _indexOfChar(j, 0x22, colonAt + 1);
        require(q1 != type(uint256).max, "no open quote");
        uint256 q2 = _indexOfChar(j, 0x22, q1 + 1);
        require(q2 != type(uint256).max, "no close quote");
        return _decodeHexWord(_slice(j, q1 + 1, q2));
    }

    function _decodeHexWord(bytes memory hexStr) internal pure returns (uint256 v) {
        uint256 from = 0;
        if (hexStr.length >= 2 && hexStr[0] == "0" && (hexStr[1] == "x" || hexStr[1] == "X")) {
            from = 2;
        }
        for (uint256 i = from; i < hexStr.length; i++) {
            v = (v << 4) | _hd(hexStr[i]);
        }
    }

    function _utoa(uint256 v) internal pure returns (string memory) {
        if (v == 0) return "0";
        uint256 tmp = v;
        uint256 digits;
        while (tmp != 0) {
            digits++;
            tmp /= 10;
        }
        bytes memory buf = new bytes(digits);
        while (v != 0) {
            digits--;
            buf[digits] = bytes1(uint8(48 + (v % 10)));
            v /= 10;
        }
        return string(buf);
    }

    function _indexOf(bytes memory haystack, bytes memory needle, uint256 start)
        internal
        pure
        returns (uint256)
    {
        if (needle.length == 0 || haystack.length < needle.length) return type(uint256).max;
        for (uint256 i = start; i + needle.length <= haystack.length; i++) {
            bool match_ = true;
            for (uint256 k = 0; k < needle.length; k++) {
                if (haystack[i + k] != needle[k]) {
                    match_ = false;
                    break;
                }
            }
            if (match_) return i;
        }
        return type(uint256).max;
    }

    function _indexOfChar(bytes memory haystack, bytes1 c, uint256 start)
        internal
        pure
        returns (uint256)
    {
        for (uint256 i = start; i < haystack.length; i++) {
            if (haystack[i] == c) return i;
        }
        return type(uint256).max;
    }

    function _slice(bytes memory s, uint256 from, uint256 to) internal pure returns (bytes memory) {
        bytes memory out = new bytes(to - from);
        for (uint256 i = 0; i < out.length; i++) out[i] = s[from + i];
        return out;
    }

    function _hd(bytes1 c) internal pure returns (uint8) {
        uint8 b = uint8(c);
        if (b >= 0x30 && b <= 0x39) return b - 0x30;
        if (b >= 0x61 && b <= 0x66) return b - 0x61 + 10;
        if (b >= 0x41 && b <= 0x46) return b - 0x41 + 10;
        revert("non-hex char");
    }
}
