// SPDX-License-Identifier: GPL-3.0-or-later
pragma solidity 0.8.24;

import { Test } from "forge-std/Test.sol";
import { QKBRegistry } from "../src/QKBRegistry.sol";
import { QKBVerifier, IGroth16Verifier } from "../src/QKBVerifier.sol";
import { QKBGroth16Verifier } from "../src/verifier/QKBGroth16Verifier.sol";
import { DeclarationHashes } from "../src/constants/DeclarationHashes.sol";

/// @notice End-to-end integration: real Groth16 proof produced by the
///         `QKBPresentationEcdsaLeaf` circuit against the real Diia admin
///         QES fixture, submitted to the real `QKBGroth16Verifier` deployed
///         alongside a real `QKBRegistry`.
///
///         Proof + public signals frozen into constants below. Source of
///         truth (regenerated by re-running the ceremony):
///           packages/circuits/build/qkb-presentation-real/proof.json
///           packages/circuits/build/qkb-presentation-real/public.json
///
///         Snarkjs quirk: `pi_b`'s inner pairs are swapped between the JSON
///         output and the Solidity verifier's argument order — the pairing
///         precompile expects `[imaginary, real]` but snarkjs writes them
///         `[real, imaginary]`. We swap on the way in.
contract QKBRegistryIntegrationTest is Test {
    QKBRegistry internal registry;
    QKBGroth16Verifier internal verifier;

    address internal constant ADMIN = address(0xA11CE);
    bytes32 internal constant INITIAL_ROOT = bytes32(uint256(0xDEADBEEF));

    // ======= Proof (pi_a, pi_b, pi_c) =========================================
    uint256 internal constant PI_A_0 = 19637039582066580511173385447575842049407090814554338962974745605997811920674;
    uint256 internal constant PI_A_1 = 9659214852248075868704269199929134141221452942604595895715568521601346320290;

    uint256 internal constant PI_B_00 = 18137252936479755399800838206742713547242323708722206292741058522461088156103;
    uint256 internal constant PI_B_01 = 9003270490984502271283610585830879838567653013046596138688122952855839305493;
    uint256 internal constant PI_B_10 = 2636952982917322659523000374833046825279844026513463036719802909409767545516;
    uint256 internal constant PI_B_11 = 17842029559096994485099931308743318367436013165877732274789711543283664726268;

    uint256 internal constant PI_C_0 = 9183477635324839786798882600233541739974663882852311504506238249670797487037;
    uint256 internal constant PI_C_1 = 11356673198742814452629997734426336748930058516913355080236381365489148687228;

    // ======= Public signals (12 — see QKBVerifier layout doc) =================
    uint256 internal constant LEAF_SPKI_COMMIT =
        21571940304476356854922994092266075334973586284547564138969104758217451997906;
    uint256 internal constant PKX_0 = 17010942108597949108;
    uint256 internal constant PKX_1 = 1991649513687774715;
    uint256 internal constant PKX_2 = 6216360143844205304;
    uint256 internal constant PKX_3 = 12257906314988956127;
    uint256 internal constant PKY_0 = 4957955114618322731;
    uint256 internal constant PKY_1 = 309974962755899423;
    uint256 internal constant PKY_2 = 16995089060621030672;
    uint256 internal constant PKY_3 = 11558558798962182750;
    uint256 internal constant CTX_HASH = 0; // empty ctx → 0 per circuit §5
    uint256 internal constant DECL_HASH =
        2835243973736894426076762873648067512237073338936951758484644120669554329750;
    uint256 internal constant TIMESTAMP = 1776390649;

    function setUp() public {
        verifier = new QKBGroth16Verifier();
        registry = new QKBRegistry(IGroth16Verifier(address(verifier)), INITIAL_ROOT, ADMIN);
        // Warp past the binding timestamp so register() doesn't reject as
        // BindingFromFuture. Stay within the 90-day MAX_AGE window.
        vm.warp(TIMESTAMP + 1 days);
    }

    function _realProof() internal pure returns (QKBVerifier.Proof memory p) {
        p.a = [PI_A_0, PI_A_1];
        // Swap inner pairs for Solidity verifier (EIP-197 pairing convention).
        p.b = [[PI_B_01, PI_B_00], [PI_B_11, PI_B_10]];
        p.c = [PI_C_0, PI_C_1];
    }

    function _realInputs() internal pure returns (QKBVerifier.Inputs memory i) {
        i.leafSpkiCommit = LEAF_SPKI_COMMIT;
        i.pkX = [PKX_0, PKX_1, PKX_2, PKX_3];
        i.pkY = [PKY_0, PKY_1, PKY_2, PKY_3];
        i.ctxHash = bytes32(CTX_HASH);
        i.declHash = bytes32(DECL_HASH);
        i.timestamp = uint64(TIMESTAMP);
    }

    function test_verify_acceptsRealProof() public view {
        QKBVerifier.Proof memory p = _realProof();
        QKBVerifier.Inputs memory i = _realInputs();
        assertTrue(QKBVerifier.verify(IGroth16Verifier(address(verifier)), p, i));
        // Sanity: the declHash in the real proof matches our whitelist.
        assertEq(i.declHash, DeclarationHashes.EN);
    }

    function test_verify_rejectsTamperedProof() public view {
        QKBVerifier.Proof memory p = _realProof();
        QKBVerifier.Inputs memory i = _realInputs();
        p.a[0] = p.a[0] ^ 1; // flip one bit
        assertFalse(QKBVerifier.verify(IGroth16Verifier(address(verifier)), p, i));
    }

    function test_verify_rejectsTamperedPublicSignals() public view {
        QKBVerifier.Proof memory p = _realProof();
        QKBVerifier.Inputs memory i = _realInputs();
        i.timestamp = i.timestamp + 1; // tamper
        assertFalse(QKBVerifier.verify(IGroth16Verifier(address(verifier)), p, i));
    }

    function test_register_acceptsRealProof() public {
        QKBVerifier.Proof memory p = _realProof();
        QKBVerifier.Inputs memory i = _realInputs();
        address pkAddr = QKBVerifier.toPkAddress(i.pkX, i.pkY);

        registry.register(p, i);

        (QKBRegistry.Status status,,, bytes32 ctxHashStored, bytes32 declHashStored) = registry.bindings(pkAddr);
        assertEq(uint8(status), uint8(QKBRegistry.Status.ACTIVE));
        assertEq(ctxHashStored, bytes32(CTX_HASH));
        assertEq(declHashStored, bytes32(DECL_HASH));
    }
}
