// Verify a contributor's uploaded zkey before publishing it to status.
//
// Usage:
//   pnpm tsx scripts/verify-contribution.ts --round 3
//
// Steps:
//   1. Download `ceremony/rounds/round-N.zkey` from R2 to a temp file.
//   2. R1CS-consistency check: `snarkjs zkey verify <r1cs> <ptau> <newZkey>`.
//   3. Chain prefix check (round ≥ 2): download round-(N-1).zkey, export
//      contribution-history JSON for both, assert new is exactly old + 1
//      contribution. Without this, a contributor could submit a fresh
//      zkey from scratch (R1CS-consistent but discarding all prior
//      ceremony entropy) and pass step 2 silently.
//   4. Compute sha256 attestation hash.
//   5. Write attestation to `pending/round-N.attestation` for publish-status.
//
// Round 1 special case: there's no round 0 contributions array beyond the
// admin seed; the chain check still runs against round 0's contributions.
// Round 0 itself is generated by `round-zero.ts`, which is admin-trusted
// and not contributor-supplied.
//
// R1CS + pot23 paths come from env: PROD_R1CS_PATH, PROD_PTAU_PATH.

import { writeFileSync, createWriteStream, mkdirSync, readFileSync, unlinkSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { spawn } from 'node:child_process';
import { parseArgs } from 'node:util';
import { Readable } from 'node:stream';
import { pipeline } from 'node:stream/promises';
import { GetObjectCommand } from '@aws-sdk/client-s3';
import { loadEnvFromAncestors } from '../src/env.ts';
import {
  loadR2Config,
  makeR2Client,
  ROUND_KEY,
} from '../src/r2.ts';

loadEnvFromAncestors(import.meta.dirname ?? process.cwd());

interface Args {
  round: number;
}

function parseCliArgs(): Args {
  const { values } = parseArgs({ options: { round: { type: 'string' } } });
  if (!values.round) throw new Error('--round required');
  const round = Number(values.round);
  if (!Number.isInteger(round) || round < 1) throw new Error('--round must be ≥ 1');
  return { round };
}

async function downloadZkey(round: number): Promise<string> {
  const cfg = loadR2Config();
  const client = makeR2Client(cfg);
  const r = await client.send(
    new GetObjectCommand({ Bucket: cfg.bucket, Key: ROUND_KEY(round) }),
  );
  if (!r.Body) throw new Error(`zkey body missing for round ${round}`);
  const out = join(tmpdir(), `round-${round}.zkey`);
  await pipeline(r.Body as Readable, createWriteStream(out));
  return out;
}

function spawnSnarkjs(args: string[]): Promise<void> {
  return new Promise((resolve, reject) => {
    const p = spawn('npx', ['snarkjs', ...args], { stdio: 'inherit' });
    p.on('exit', (code) =>
      code === 0
        ? resolve()
        : reject(new Error(`snarkjs ${args.join(' ')} exit ${code}`)),
    );
    p.on('error', reject);
  });
}

async function snarkjsR1csVerify(zkeyPath: string): Promise<void> {
  const r1cs = process.env.PROD_R1CS_PATH;
  const ptau = process.env.PROD_PTAU_PATH;
  if (!r1cs) throw new Error('PROD_R1CS_PATH not set');
  if (!ptau) throw new Error('PROD_PTAU_PATH not set');
  await spawnSnarkjs(['zkey', 'verify', r1cs, ptau, zkeyPath]);
}

interface ZkeyContribution {
  readonly name?: string;
  readonly contributionHash?: string;
  readonly type?: number;
  // snarkjs's exact JSON shape varies by version; we treat each
  // contribution as opaque + compare via deep-equal canonical JSON.
  readonly [k: string]: unknown;
}

interface ZkeyExport {
  readonly contributions: readonly ZkeyContribution[];
  // Other fields (verification key constants, etc.) are not used here.
  readonly [k: string]: unknown;
}

async function exportZkeyJson(zkeyPath: string): Promise<ZkeyExport> {
  const out = `${zkeyPath}.json`;
  await spawnSnarkjs(['zkey', 'export', 'json', zkeyPath, out]);
  const parsed = JSON.parse(readFileSync(out, 'utf-8')) as unknown;
  unlinkSync(out);
  if (
    typeof parsed !== 'object' ||
    parsed === null ||
    !('contributions' in parsed) ||
    !Array.isArray((parsed as { contributions: unknown }).contributions)
  ) {
    throw new Error(`zkey export json shape unexpected: ${zkeyPath}`);
  }
  return parsed as ZkeyExport;
}

/**
 * Chain prefix check: assert that `newZkey`'s contributions array is
 * exactly `oldZkey`'s contributions array + 1 new entry. Defends
 * against the "contributor submits a fresh zkey from scratch" attack
 * — that fresh zkey would be R1CS-consistent (passing snarkjsR1csVerify)
 * but would discard all prior ceremony entropy.
 */
async function snarkjsChainVerify(
  prevZkeyPath: string,
  newZkeyPath: string,
): Promise<void> {
  const prev = await exportZkeyJson(prevZkeyPath);
  const next = await exportZkeyJson(newZkeyPath);

  if (next.contributions.length !== prev.contributions.length + 1) {
    throw new Error(
      `chain length mismatch: prev has ${prev.contributions.length} contributions, ` +
        `new has ${next.contributions.length} (expected ${prev.contributions.length + 1})`,
    );
  }

  for (let i = 0; i < prev.contributions.length; i++) {
    const p = JSON.stringify(prev.contributions[i]);
    const n = JSON.stringify(next.contributions[i]);
    if (p !== n) {
      throw new Error(
        `chain mismatch at contribution[${i}]: contributor produced a fresh ` +
          `zkey instead of contributing on top of round ${i}. Reject.`,
      );
    }
  }
}

async function sha256OfFile(path: string): Promise<string> {
  const { createReadStream } = await import('node:fs');
  const hash = createHash('sha256');
  await pipeline(createReadStream(path), hash);
  return hash.digest('hex');
}

async function main(): Promise<void> {
  const args = parseCliArgs();

  console.log(`Downloading round-${args.round}.zkey from R2…`);
  const newZkeyPath = await downloadZkey(args.round);
  console.log(`Downloaded to ${newZkeyPath}`);

  console.log('Step 1/3: snarkjs zkey verify (R1CS-consistency)…');
  await snarkjsR1csVerify(newZkeyPath);
  console.log('R1CS-consistency PASSED.');

  console.log(`Step 2/3: chain-prefix check against round-${args.round - 1}.zkey…`);
  const prevRound = args.round - 1;
  const prevZkeyPath = await downloadZkey(prevRound);
  await snarkjsChainVerify(prevZkeyPath, newZkeyPath);
  console.log(`Chain-prefix check PASSED — round ${args.round} extends round ${prevRound}.`);

  console.log('Step 3/3: sha256 attestation…');
  const sha = await sha256OfFile(newZkeyPath);
  console.log(`sha256: ${sha}`);

  const attestationDir = join(import.meta.dirname ?? '.', '..', 'pending');
  mkdirSync(attestationDir, { recursive: true });
  const attestationFile = join(attestationDir, `round-${args.round}.attestation`);
  writeFileSync(
    attestationFile,
    JSON.stringify(
      {
        round: args.round,
        sha256: sha,
        verifiedAt: new Date().toISOString(),
        chainVerifiedAgainst: prevRound,
      },
      null,
      2,
    ),
  );
  console.log(`Attestation written to ${attestationFile}`);
  console.log(`\nNext: pnpm tsx scripts/publish-status.ts --round ${args.round} --commit`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
