// SPDX-License-Identifier: GPL-3.0-or-later
//
// Generator for the Poseidon contract initcode (EVM bytecode that, when
// deployed, exposes a `poseidon(uint256[N])` pure function over BN254 Fr).
// Output is committed in-source via PoseidonBytecode.sol; the registry
// CREATE-deploys these constants in its constructor and stashes the
// resulting addresses as immutables.
//
// Provenance: this script wraps `createCode(nInputs)` from
// `circomlibjs/src/poseidon_gencontract.js` (GPL-3.0, pinned via the
// pnpm-lock.yaml entry for circomlibjs@0.1.7). circomlibjs is the
// canonical Poseidon-EVM emitter — it pre-dates vimwitch, was authored by
// the iden3 team alongside the original Poseidon paper + circomlib
// reference impl, and is the upstream that every other emitter
// (vimwitch, etc.) is descended from. Constants are circomlib's
// published BN254 round constants + MDS matrix.
//
// Why bytecode emission rather than in-tree Solidity:
//   The pure-Solidity Poseidon ecosystem (vimwitch's PoseidonT_n, our
//   own attempted in-tree generator) compiles only WITHOUT via_ir. Our
//   foundry.toml has via_ir=true because the V4 snarkjs-emitted Groth16
//   verifier requires it. Per-file compiler-settings overrides aren't
//   exposed by Forge, so the only paths that compile under via_ir are
//   (a) bytecode-deployed Poseidon called via staticcall, or (b) splitting
//   Poseidon into a separate sub-package. (a) wins on simplicity.
//
// Reproducibility — the V5 Forge test
// `test/PoseidonBytecodeReproducibility.t.sol` runs this script, captures
// stdout, and asserts byte-equality with PoseidonBytecode.sol's constants.
// If the generator's output ever diverges from what's in source, that test
// fails loudly. Auditors verify provenance by re-running the script.

import { createCode } from "../../../node_modules/.pnpm/circomlibjs@0.1.7_bufferutil@4.1.0_utf-8-validate@5.0.10/node_modules/circomlibjs/src/poseidon_gencontract.js";

interface Target {
  nInputs: number;
  t: number;
}

// V5 SpkiCommit needs Poseidon₆ (over the 6 limbs of each coordinate, t=7)
// and Poseidon₂ (over the two intermediate hashes, t=3).
const TARGETS: Target[] = [
  { nInputs: 2, t: 3 }, // PoseidonT3
  { nInputs: 6, t: 7 }, // PoseidonT7
];

interface EmitMode {
  format: "json" | "solidity";
}

function parseArgs(): EmitMode {
  const fmt = process.argv.includes("--solidity") ? "solidity" : "json";
  return { format: fmt };
}

function emitJson() {
  const out: Record<string, { nInputs: number; t: number; bytecodeHex: string; lengthBytes: number }> = {};
  for (const tgt of TARGETS) {
    const code: string = createCode(tgt.nInputs);
    if (!code.startsWith("0x")) throw new Error(`unexpected createCode output: ${code.slice(0, 40)}`);
    const lenHex = code.length - 2;
    if (lenHex % 2 !== 0) throw new Error(`createCode hex string has odd length: ${lenHex}`);
    out[`PoseidonT${tgt.t}`] = {
      nInputs: tgt.nInputs,
      t: tgt.t,
      bytecodeHex: code,
      lengthBytes: lenHex / 2,
    };
  }
  process.stdout.write(JSON.stringify(out, null, 2) + "\n");
}

function emitSolidity() {
  // Render the entire PoseidonBytecode.sol file. This is what gets piped
  // into src/libs/PoseidonBytecode.sol and what the reproducibility test
  // diff-asserts against.
  const lines: string[] = [];
  lines.push("// SPDX-License-Identifier: GPL-3.0-or-later");
  lines.push("// AUTOGENERATED — DO NOT EDIT.");
  lines.push("// Source: packages/contracts/script/generate-poseidon-bytecode.ts");
  lines.push(
    "// Generator: circomlibjs@0.1.7 src/poseidon_gencontract.js (GPL-3.0).",
  );
  lines.push("// To regenerate:");
  lines.push("//   pnpm tsx packages/contracts/script/generate-poseidon-bytecode.ts --solidity \\");
  lines.push("//     > packages/contracts/src/libs/PoseidonBytecode.sol");
  lines.push("pragma solidity 0.8.24;");
  lines.push("");
  lines.push("/// @notice Initcode constants for Poseidon hashes over BN254 Fr.");
  lines.push("/// @dev    Each constant is the deploy-initcode (init + runtime) for a");
  lines.push("///         contract exposing `poseidon(uint256[N])` pure-view-callable");
  lines.push("///         from staticcall. Deployed once per registry instance via CREATE");
  lines.push("///         in the registry's constructor; addresses cached as immutables.");
  lines.push("library PoseidonBytecode {");

  // Chunk size — solc 0.8.24's parser segfaults on very large `hex"..."`
  // literals (observed at 47K hex chars on a single token). Splitting into
  // ~4KB hex literals (= 2K bytes per chunk) joined via bytes.concat keeps
  // each token below the parser's stress point and produces cleaner audit
  // diffs (each chunk fits on a few lines).
  const HEX_CHUNK_CHARS = 4096;

  for (const tgt of TARGETS) {
    const code: string = createCode(tgt.nInputs);
    if (!code.startsWith("0x")) throw new Error(`unexpected createCode output: ${code.slice(0, 40)}`);
    const hex = code.slice(2);
    const lengthBytes = hex.length / 2;
    const chunks: string[] = [];
    for (let i = 0; i < hex.length; i += HEX_CHUNK_CHARS) {
      chunks.push(hex.slice(i, i + HEX_CHUNK_CHARS));
    }

    lines.push("");
    lines.push(`    /// PoseidonT${tgt.t} — t=${tgt.t}, ${tgt.nInputs} inputs.`);
    lines.push(`    /// Initcode size: ${lengthBytes} bytes (${chunks.length} hex chunks of ≤${HEX_CHUNK_CHARS / 2} bytes each).`);
    lines.push(`    /// Solidity ABI: function poseidon(uint256[${tgt.nInputs}]) external pure returns (uint256)`);
    lines.push(`    function t${tgt.t}Initcode() internal pure returns (bytes memory) {`);
    if (chunks.length === 1) {
      lines.push(`        return hex"${chunks[0]}";`);
    } else {
      lines.push("        return bytes.concat(");
      for (let i = 0; i < chunks.length; i++) {
        const sep = i === chunks.length - 1 ? "" : ",";
        lines.push(`            hex"${chunks[i]}"${sep}`);
      }
      lines.push("        );");
    }
    lines.push("    }");
  }

  lines.push("}");
  lines.push("");
  process.stdout.write(lines.join("\n"));
}

function main() {
  const mode = parseArgs();
  if (mode.format === "solidity") emitSolidity();
  else emitJson();
}

main();
